[versions]
assertj = "3.27.6"
kotlin-gradle-plugin = "2.3.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
gradle-extensions = { module = "io.technoirlab.conventions:gradle-extensions" }
gradle-test-kit = { module = "io.technoirlab.conventions:gradle-test-kit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json" }
