name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Build with Gradle
        run: ./gradlew build --scan

  actions-lint:
    name: Lint workflows
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1.68.0
        with:
          level: warning
          fail_level: error
